### ISSUE TITLE
The Quickstart docker-compose.yml file has connection refused errors after startup on 5001

### ISSUE THREAD

**Issue by jsdevel** [ipfs/ipfs-cluster#1503]
**Additional information:**
 - OS: [e.g. Linux] Linux localhost.localdomain 5.15.4-101.fc34.x86_64 #1 SMP Tue Nov 23 18:58:50 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - IPFS Cluster version: [e.g. 0.10.1, master] 0.14.1
 - Installation method: [e.g. built from source, dist.ipfs.io, docker] docker

**Describe the bug:**

After running `docker-compose up` with the provided docker-compose.yml file int he quickstart guide, `./ipfs-cluster-ctl add foo.txt` fails.  Un-commenting the ports block in the compose file doesn't help.

Here's the log output:

```
cluster1    | 2021-11-30T22:17:36.930Z	ERROR	ipfshttp	ipfshttp/ipfshttp.go:584	error posting to IPFS:Post "http://172.18.0.4:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.4:5001: connect: connection refused
cluster1    | 2021-11-30T22:17:36.930Z	ERROR	ipfshttp	ipfshttp/ipfshttp.go:746	Post "http://172.18.0.4:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.4:5001: connect: connection refused
cluster1    | 2021-11-30T22:17:36.930Z	ERROR	p2p-gorpc	go-libp2p-gorpc@v0.1.3/call.go:63	Post "http://172.18.0.4:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.4:5001: connect: connection refused
cluster1    | 2021-11-30T22:17:36.930Z	ERROR	diskinfo	disk/disk.go:119	Post "http://172.18.0.4:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.4:5001: connect: connection refused
cluster1    | 2021-11-30T22:17:36.931Z	WARN	monitor	pubsubmon/pubsubmon.go:218	discarding invalid metric: &{Name:freespace Peer:12D3KooWH9rFyae4JaKgvLZQ4x4mhmsD4frfrfKZ9893YM3tGVdn Value:0 Expire:1638310686930984254 Valid:false Weight:0 Partitionable:false ReceivedAt:0}
cluster2    | 2021-11-30T22:17:36.981Z	ERROR	ipfshttp	ipfshttp/ipfshttp.go:584	error posting to IPFS:Post "http://172.18.0.2:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.2:5001: connect: connection refused
cluster2    | 2021-11-30T22:17:36.981Z	ERROR	ipfshttp	ipfshttp/ipfshttp.go:746	Post "http://172.18.0.2:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.2:5001: connect: connection refused
cluster2    | 2021-11-30T22:17:36.981Z	ERROR	p2p-gorpc	go-libp2p-gorpc@v0.1.3/call.go:63	Post "http://172.18.0.2:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.2:5001: connect: connection refused
cluster2    | 2021-11-30T22:17:36.981Z	ERROR	diskinfo	disk/disk.go:119	Post "http://172.18.0.2:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.2:5001: connect: connection refused
cluster2    | 2021-11-30T22:17:36.981Z	WARN	monitor	pubsubmon/pubsubmon.go:218	discarding invalid metric: &{Name:freespace Peer:12D3KooWDkpCyjt3CyUKS4F7bccg2y27r65i7GBE56bNCDk7AaeK Value:0 Expire:1638310686981482444 Valid:false Weight:0 Partitionable:false ReceivedAt:0}
cluster0    | 2021-11-30T22:17:37.937Z	ERROR	ipfshttp	ipfshttp/ipfshttp.go:584	error posting to IPFS:Post "http://172.18.0.2:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.2:5001: connect: connection refused
cluster0    | 2021-11-30T22:17:37.937Z	ERROR	ipfshttp	ipfshttp/ipfshttp.go:746	Post "http://172.18.0.2:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.2:5001: connect: connection refused
cluster0    | 2021-11-30T22:17:37.937Z	ERROR	p2p-gorpc	go-libp2p-gorpc@v0.1.3/call.go:63	Post "http://172.18.0.2:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.2:5001: connect: connection refused
cluster0    | 2021-11-30T22:17:37.937Z	ERROR	diskinfo	disk/disk.go:119	Post "http://172.18.0.2:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.2:5001: connect: connection refused
cluster0    | 2021-11-30T22:17:37.937Z	WARN	monitor	pubsubmon/pubsubmon.go:218	discarding invalid metric: &{Name:freespace Peer:12D3KooWMP7ptp1isHssvCVG1yjEL91kgLvpeDw3V29wxBs4EXQB Value:0 Expire:1638310687937857018 Valid:false Weight:0 Partitionable:false ReceivedAt:0}
cluster1    | 2021-11-30T22:17:51.932Z	ERROR	ipfshttp	ipfshttp/ipfshttp.go:584	error posting to IPFS:Post "http://172.18.0.4:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.4:5001: connect: connection refused
cluster1    | 2021-11-30T22:17:51.932Z	ERROR	ipfshttp	ipfshttp/ipfshttp.go:746	Post "http://172.18.0.4:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.4:5001: connect: connection refused
cluster1    | 2021-11-30T22:17:51.932Z	ERROR	p2p-gorpc	go-libp2p-gorpc@v0.1.3/call.go:63	Post "http://172.18.0.4:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.4:5001: connect: connection refused
cluster1    | 2021-11-30T22:17:51.932Z	ERROR	diskinfo	disk/disk.go:119	Post "http://172.18.0.4:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.4:5001: connect: connection refused
cluster1    | 2021-11-30T22:17:51.932Z	WARN	monitor	pubsubmon/pubsubmon.go:218	discarding invalid metric: &{Name:freespace Peer:12D3KooWH9rFyae4JaKgvLZQ4x4mhmsD4frfrfKZ9893YM3tGVdn Value:0 Expire:1638310701932602520 Valid:false Weight:0 Partitionable:false ReceivedAt:0}
cluster2    | 2021-11-30T22:17:51.982Z	ERROR	ipfshttp	ipfshttp/ipfshttp.go:584	error posting to IPFS:Post "http://172.18.0.2:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.2:5001: connect: connection refused
cluster2    | 2021-11-30T22:17:51.982Z	ERROR	ipfshttp	ipfshttp/ipfshttp.go:746	Post "http://172.18.0.2:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.2:5001: connect: connection refused
cluster2    | 2021-11-30T22:17:51.982Z	ERROR	p2p-gorpc	go-libp2p-gorpc@v0.1.3/call.go:63	Post "http://172.18.0.2:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.2:5001: connect: connection refused
cluster2    | 2021-11-30T22:17:51.982Z	ERROR	diskinfo	disk/disk.go:119	Post "http://172.18.0.2:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.2:5001: connect: connection refused
cluster2    | 2021-11-30T22:17:51.982Z	WARN	monitor	pubsubmon/pubsubmon.go:218	discarding invalid metric: &{Name:freespace Peer:12D3KooWDkpCyjt3CyUKS4F7bccg2y27r65i7GBE56bNCDk7AaeK Value:0 Expire:1638310701982532800 Valid:false Weight:0 Partitionable:false ReceivedAt:0}
cluster0    | 2021-11-30T22:17:52.939Z	ERROR	ipfshttp	ipfshttp/ipfshttp.go:584	error posting to IPFS:Post "http://172.18.0.2:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.2:5001: connect: connection refused
cluster0    | 2021-11-30T22:17:52.939Z	ERROR	ipfshttp	ipfshttp/ipfshttp.go:746	Post "http://172.18.0.2:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.2:5001: connect: connection refused
cluster0    | 2021-11-30T22:17:52.939Z	ERROR	p2p-gorpc	go-libp2p-gorpc@v0.1.3/call.go:63	Post "http://172.18.0.2:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.2:5001: connect: connection refused
cluster0    | 2021-11-30T22:17:52.939Z	ERROR	diskinfo	disk/disk.go:119	Post "http://172.18.0.2:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.2:5001: connect: connection refused
cluster0    | 2021-11-30T22:17:52.940Z	WARN	monitor	pubsubmon/pubsubmon.go:218	discarding invalid metric: &{Name:freespace Peer:12D3KooWMP7ptp1isHssvCVG1yjEL91kgLvpeDw3V29wxBs4EXQB Value:0 Expire:1638310702940028439 Valid:false Weight:0 Partitionable:false ReceivedAt:0}
```

**Comment by hsanjuan** [comment]
are the ipfs containers running?

**Comment by jsdevel** [comment]
yes

**Comment by hsanjuan** [comment]
```
[00:09:39] ~/g/s/g/i/ipfs-cluster (master|…5) $ docker exec -ti cluster0 sh
/ # echo aaa> foo.txt
/ # ipfs-cluster-ctl add foo.txt
added QmUzA3j2VBbmajMVJwCL5JYim86WaJuAj5B4HVWpFyQZLV foo.txt
```

works for me...

In any case, non of the errors you paste are related to adding. They are related to cluster peers trying to get information from IPFS. I see some of those during launch in the time when the cluster peer has just started but the ipfs peer has not, but then they go away.

**Comment by jsdevel** [comment]
yea, seems to be docker related

**Comment by jsdevel** [comment]
```
ipfs-cluster-ctl $ ./ipfs-cluster-ctl peers ls
12D3KooWDkpCyjt3CyUKS4F7bccg2y27r65i7GBE56bNCDk7AaeK | cluster2 | Sees 2 other peers
  > Addresses:
    - /ip4/127.0.0.1/tcp/9096/p2p/12D3KooWDkpCyjt3CyUKS4F7bccg2y27r65i7GBE56bNCDk7AaeK
    - /ip4/172.18.0.5/tcp/9096/p2p/12D3KooWDkpCyjt3CyUKS4F7bccg2y27r65i7GBE56bNCDk7AaeK
  > IPFS ERROR: Post "http://172.18.0.2:5001/api/v0/id": dial tcp 172.18.0.2:5001: connect: connection refused
12D3KooWH9rFyae4JaKgvLZQ4x4mhmsD4frfrfKZ9893YM3tGVdn | cluster1 | Sees 2 other peers
  > Addresses:
    - /ip4/127.0.0.1/tcp/9096/p2p/12D3KooWH9rFyae4JaKgvLZQ4x4mhmsD4frfrfKZ9893YM3tGVdn
    - /ip4/172.18.0.7/tcp/9096/p2p/12D3KooWH9rFyae4JaKgvLZQ4x4mhmsD4frfrfKZ9893YM3tGVdn
  > IPFS ERROR: Post "http://172.18.0.4:5001/api/v0/id": dial tcp 172.18.0.4:5001: connect: connection refused
12D3KooWMP7ptp1isHssvCVG1yjEL91kgLvpeDw3V29wxBs4EXQB | cluster0 | Sees 2 other peers
  > Addresses:
    - /ip4/127.0.0.1/tcp/9096/p2p/12D3KooWMP7ptp1isHssvCVG1yjEL91kgLvpeDw3V29wxBs4EXQB
    - /ip4/172.18.0.6/tcp/9096/p2p/12D3KooWMP7ptp1isHssvCVG1yjEL91kgLvpeDw3V29wxBs4EXQB
  > IPFS ERROR: Post "http://172.18.0.3:5001/api/v0/id": dial tcp 172.18.0.3:5001: connect: connection refused
```

**Comment by jsdevel** [comment]
this appears to be an issue with docker networking i'm guessing

**Comment by hsanjuan** [comment]
connection refused suggests the container is there but perhaps ipfs is not listening... I'm not really sure... cannot reproduce.

**Comment by jsdevel** [comment]
```
ipfs-cluster-ctl $ docker-compose ps
  Name                Command               State                        Ports                      
----------------------------------------------------------------------------------------------------
cluster0   /sbin/tini -- /usr/local/b ...   Up      127.0.0.1:9094->9094/tcp, 9095/tcp, 9096/tcp    
cluster1   /sbin/tini -- /usr/local/b ...   Up      9094/tcp, 9095/tcp, 9096/tcp                    
cluster2   /sbin/tini -- /usr/local/b ...   Up      9094/tcp, 9095/tcp, 9096/tcp                    
ipfs0      /sbin/tini -- /usr/local/b ...   Up      4001/tcp, 4001/udp, 5001/tcp, 8080/tcp, 8081/tcp
ipfs1      /sbin/tini -- /usr/local/b ...   Up      4001/tcp, 4001/udp, 5001/tcp, 8080/tcp, 8081/tcp
ipfs2      /sbin/tini -- /usr/local/b ...   Up      4001/tcp, 4001/udp, 5001/tcp, 8080/tcp, 8081/tcp
```

@hsanjuan can you share what yous ee?

**Comment by hsanjuan** [comment]
can you check the ipfs logs to see it listens?

**Comment by jsdevel** [comment]
```
ipfs0       | Swarm listening on /ip4/127.0.0.1/tcp/4001
ipfs0       | Swarm listening on /ip4/127.0.0.1/udp/4001/quic
ipfs0       | Swarm listening on /ip4/172.18.0.3/tcp/4001
ipfs0       | Swarm listening on /ip4/172.18.0.3/udp/4001/quic
ipfs0       | Swarm listening on /p2p-circuit
ipfs0       | Swarm announcing /ip4/127.0.0.1/tcp/4001
ipfs0       | Swarm announcing /ip4/127.0.0.1/udp/4001/quic
ipfs0       | Swarm announcing /ip4/172.18.0.3/tcp/4001
ipfs0       | Swarm announcing /ip4/172.18.0.3/udp/4001/quic
ipfs0       | API server listening on /ip4/127.0.0.1/tcp/5001
ipfs0       | WebUI: http://127.0.0.1:5001/webui
ipfs0       | Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
ipfs0       | Daemon is ready
ipfs2       | Swarm listening on /ip4/127.0.0.1/tcp/4001
ipfs2       | Swarm listening on /ip4/127.0.0.1/udp/4001/quic
ipfs2       | Swarm listening on /ip4/172.18.0.2/tcp/4001
ipfs2       | Swarm listening on /ip4/172.18.0.2/udp/4001/quic
ipfs2       | Swarm listening on /p2p-circuit
ipfs2       | Swarm announcing /ip4/127.0.0.1/tcp/4001
ipfs2       | Swarm announcing /ip4/127.0.0.1/udp/4001/quic
ipfs2       | Swarm announcing /ip4/172.18.0.2/tcp/4001
ipfs2       | Swarm announcing /ip4/172.18.0.2/udp/4001/quic
ipfs2       | API server listening on /ip4/127.0.0.1/tcp/5001
ipfs2       | WebUI: http://127.0.0.1:5001/webui
ipfs2       | Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
ipfs2       | Daemon is ready
ipfs1       | Swarm listening on /ip4/127.0.0.1/tcp/4001
ipfs1       | Swarm listening on /ip4/127.0.0.1/udp/4001/quic
ipfs1       | Swarm listening on /ip4/172.18.0.4/tcp/4001
ipfs1       | Swarm listening on /ip4/172.18.0.4/udp/4001/quic
ipfs1       | Swarm listening on /p2p-circuit
ipfs1       | Swarm announcing /ip4/127.0.0.1/tcp/4001
ipfs1       | Swarm announcing /ip4/127.0.0.1/udp/4001/quic
ipfs1       | Swarm announcing /ip4/172.18.0.4/tcp/4001
ipfs1       | Swarm announcing /ip4/172.18.0.4/udp/4001/quic
ipfs1       | API server listening on /ip4/127.0.0.1/tcp/5001
ipfs1       | WebUI: http://127.0.0.1:5001/webui
ipfs1       | Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
ipfs1       | Daemon is ready
```

**Comment by jsdevel** [comment]
i'm continually seeing this:

```
cluster0    | 2021-12-01T15:51:07.983Z	ERROR	ipfshttp	ipfshttp/ipfshttp.go:584	error posting to IPFS:Post "http://172.18.0.3:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.3:5001: connect: connection refused
cluster0    | 2021-12-01T15:51:07.984Z	ERROR	ipfshttp	ipfshttp/ipfshttp.go:746	Post "http://172.18.0.3:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.3:5001: connect: connection refused
cluster0    | 2021-12-01T15:51:07.984Z	ERROR	p2p-gorpc	go-libp2p-gorpc@v0.1.3/call.go:63	Post "http://172.18.0.3:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.3:5001: connect: connection refused
cluster0    | 2021-12-01T15:51:07.984Z	ERROR	diskinfo	disk/disk.go:119	Post "http://172.18.0.3:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.3:5001: connect: connection refused
cluster0    | 2021-12-01T15:51:07.984Z	WARN	monitor	pubsubmon/pubsubmon.go:218	discarding invalid metric: &{Name:freespace Peer:12D3KooWMP7ptp1isHssvCVG1yjEL91kgLvpeDw3V29wxBs4EXQB Value:0 Expire:1638373897984275223 Valid:false Weight:0 Partitionable:false ReceivedAt:0}
cluster2    | 2021-12-01T15:51:08.164Z	ERROR	ipfshttp	ipfshttp/ipfshttp.go:584	error posting to IPFS:Post "http://172.18.0.2:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.2:5001: connect: connection refused
cluster2    | 2021-12-01T15:51:08.164Z	ERROR	ipfshttp	ipfshttp/ipfshttp.go:746	Post "http://172.18.0.2:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.2:5001: connect: connection refused
cluster2    | 2021-12-01T15:51:08.164Z	ERROR	p2p-gorpc	go-libp2p-gorpc@v0.1.3/call.go:63	Post "http://172.18.0.2:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.2:5001: connect: connection refused
cluster2    | 2021-12-01T15:51:08.164Z	ERROR	diskinfo	disk/disk.go:119	Post "http://172.18.0.2:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.2:5001: connect: connection refused
cluster2    | 2021-12-01T15:51:08.164Z	WARN	monitor	pubsubmon/pubsubmon.go:218	discarding invalid metric: &{Name:freespace Peer:12D3KooWDkpCyjt3CyUKS4F7bccg2y27r65i7GBE56bNCDk7AaeK Value:0 Expire:1638373898164698293 Valid:false Weight:0 Partitionable:false ReceivedAt:0}
cluster1    | 2021-12-01T15:51:08.169Z	ERROR	ipfshttp	ipfshttp/ipfshttp.go:584	error posting to IPFS:Post "http://172.18.0.4:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.4:5001: connect: connection refused
cluster1    | 2021-12-01T15:51:08.169Z	ERROR	ipfshttp	ipfshttp/ipfshttp.go:746	Post "http://172.18.0.4:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.4:5001: connect: connection refused
cluster1    | 2021-12-01T15:51:08.169Z	ERROR	p2p-gorpc	go-libp2p-gorpc@v0.1.3/call.go:63	Post "http://172.18.0.4:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.4:5001: connect: connection refused
cluster1    | 2021-12-01T15:51:08.169Z	ERROR	diskinfo	disk/disk.go:119	Post "http://172.18.0.4:5001/api/v0/repo/stat?size-only=true": dial tcp 172.18.0.4:5001: connect: connection refused
cluster1    | 2021-12-01T15:51:08.169Z	WARN	monitor	pubsubmon/pubsubmon.go:218	discarding invalid metric: &{Name:freespace Peer:12D3KooWH9rFyae4JaKgvLZQ4x4mhmsD4frfrfKZ9893YM3tGVdn Value:0 Expire:1638373898169760581 Valid:false Weight:0 Partitionable:false ReceivedAt:0}
```

**Comment by jsdevel** [comment]
i think the ipfs services are up because of this:

```
ipfs-cluster-ctl $ docker exec -it ipfs1 telnet 0.0.0.0 5001
Connected to 0.0.0.0
```

**Comment by jsdevel** [comment]
here's this:

```
ipfs-cluster-ctl $ docker inspect ipfs-cluster-ctl_default
[
    {
        "Name": "ipfs-cluster-ctl_default",
        "Id": "1334b4124267dfffc5ff8c861b42dbb19c0a0f1ca1538c80edfa8023e1abeeeb",
        "Created": "2021-11-30T11:57:03.664060169-07:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "5e8fa460964a27b13c837c3acdd6e21cd2e092c9582343f6e39ff79374cc58d4": {
                "Name": "ipfs0",
                "EndpointID": "564f8cb7b3978ef26c2735b9f156e1e051a5404c2d6ef734a657478b3fc9c9bd",
                "MacAddress": "02:42:ac:12:00:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            },
            "74b114872e905ef6bd28a235ecf0ca6edcee710df213c2983355efd3f90352aa": {
                "Name": "cluster0",
                "EndpointID": "f4f968e7622197d8670a4cadbc20e3f40c8673f1996619de47ef9a867a060535",
                "MacAddress": "02:42:ac:12:00:06",
                "IPv4Address": "172.18.0.6/16",
                "IPv6Address": ""
            },
            "a82207cbd10a9508335d0cf117c100d639f74116177c89c85c821237d045e1bf": {
                "Name": "ipfs1",
                "EndpointID": "07c92da067a5242b0603fe79d9d6418f27f64df975231272ee78fc703cec63bd",
                "MacAddress": "02:42:ac:12:00:04",
                "IPv4Address": "172.18.0.4/16",
                "IPv6Address": ""
            },
            "b3184b39389dc306dd6f3f8bbecef7c8cc2bdd222216a7d85f8a233862e6e3a8": {
                "Name": "cluster2",
                "EndpointID": "f5a524bc5ab198ab60479059fdf4a730a11a1f3ccc1521d11c9223a56d0038c6",
                "MacAddress": "02:42:ac:12:00:05",
                "IPv4Address": "172.18.0.5/16",
                "IPv6Address": ""
            },
            "bd4f0e852d79553efcda8be48cb530b8f7ccaf21ce4e5d97f157a2e912ccc51d": {
                "Name": "ipfs2",
                "EndpointID": "bf9a61af5431d3dcda43ce85b75fad346265c3a227d485c111ccf7ab17ecc8c0",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            },
            "df12828542c0040fd388be381ea96992ad5bc34241332fb077dd43f0b1e5396f": {
                "Name": "cluster1",
                "EndpointID": "0cee5379695d6d99b630ca0a1506b7ee36fe05b56303840a41975eabd5a6b3c2",
                "MacAddress": "02:42:ac:12:00:07",
                "IPv4Address": "172.18.0.7/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "ipfs-cluster-ctl",
            "com.docker.compose.version": "1.28.6"
        }
    }
]
```

**Comment by jsdevel** [comment]
```
ipfs-cluster-ctl $ docker-compose --version
docker-compose version 1.28.6, build unknown
```

```
ipfs-cluster-ctl $ docker --version
Docker version 20.10.11, build 485636f
```

**Comment by jsdevel** [comment]
```
version: '3.4'

# This is an example docker-compose file to quickly test an IPFS Cluster
# with multiple peers on a contained environment.

# It runs 3 cluster peers (cluster0, cluster1...) attached to go-ipfs daemons
# (ipfs0, ipfs1...) using the CRDT consensus component. Cluster peers
# autodiscover themselves using mDNS on the docker internal network.
#
# To interact with the cluster use "ipfs-cluster-ctl" (the cluster0 API port is
# exposed to the locahost. You can also "docker exec -ti cluster0 sh" and run
# it from the container. "ipfs-cluster-ctl peers ls" should show all 3 peers a few
# seconds after start.
#
# For persistance, a "compose" folder is created and used to store configurations
# and states. This can be used to edit configurations in subsequent runs. It looks
# as follows:
#
# compose/
# |-- cluster0
# |-- cluster1
# |-- ...
# |-- ipfs0
# |-- ipfs1
# |-- ...
#
# During the first start, default configurations are created for all peers.

services:

##################################################################################
## Cluster PEER 0 ################################################################
##################################################################################

  ipfs0:
    container_name: ipfs0
    image: ipfs/go-ipfs:latest
    expose:
      - "5001"
      - "4001"
    # ports:
    # - "5001" # ipfs api - expose if needed/wanted
    # - "4001" # ipfs swarm - expose if needed/wanted
    # - "8080:8080" # ipfs gateway - expose if needed/wanted
    volumes:
      - ./compose/ipfs0:/data/ipfs:z

  cluster0:
    container_name: cluster0
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs0
    environment:
      CLUSTER_PEERNAME: cluster0
      CLUSTER_SECRET: ${CLUSTER_SECRET} # From shell variable if set
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs0/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    ports:
          # Open API port (allows ipfs-cluster-ctl usage on host)
          - "127.0.0.1:9094:9094"
          # The cluster swarm port would need  to be exposed if this container
          # was to connect to cluster peers on other hosts.
          # But this is just a testing cluster.
          # - "9096:9096" # Cluster IPFS Proxy endpoint
    volumes:
      - ./compose/cluster0:/data/ipfs-cluster:z

##################################################################################
## Cluster PEER 1 ################################################################
##################################################################################

# See Cluster PEER 0 for comments (all removed here and below)
  ipfs1:
    container_name: ipfs1
    image: ipfs/go-ipfs:latest
    expose:
      - "5001"
      - "4001"
    volumes:
      - ./compose/ipfs1:/data/ipfs:z

  cluster1:
    container_name: cluster1
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs1
    environment:
      CLUSTER_PEERNAME: cluster1
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs1/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster1:/data/ipfs-cluster:z

##################################################################################
## Cluster PEER 2 ################################################################
##################################################################################

# See Cluster PEER 0 for comments (all removed here and below)
  ipfs2:
    container_name: ipfs2
    image: ipfs/go-ipfs:latest
    expose:
      - "5001"
      - "4001"
    volumes:
      - ./compose/ipfs2:/data/ipfs:z

  cluster2:
    container_name: cluster2
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs2
    environment:
      CLUSTER_PEERNAME: cluster2
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs2/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster2:/data/ipfs-cluster:z

# For adding more peers, copy PEER 1 and rename things to ipfs2, cluster2.
# Keep bootstrapping to cluster0.
```
