### ISSUE TITLE
Inconsistencies / 0.3.5 breaking behaviour with Docker image.

### ISSUE THREAD

**Issue by hickscorp** [ipfs/ipfs-cluster#376]
**The following post is outdated, and there are partial answers on my next comment. There is a working bit of docker-compose configuration and succint explanation.**

Given the following fig definition:

```
version: '3'

networks:
  ipfs:

services:
  ipfs-peer-one:
    image: ipfs/ipfs-cluster:v0.3.0
    networks:
      - ipfs
    ports:
      - '8080:8080'
      - '4001:4001'
      - '5001:5001'
    volumes:
      - ./_data/ipfs-peer-one/config:/data/ipfs-cluster

  ipfs-peer-two:
    image: ipfs/ipfs-cluster:v0.3.0
    networks:
      - ipfs
    ports:
      - '8081:8080'
      - '4002:4001'
      - '5002:5001'
    volumes:
      - ./_data/ipfs-peer-two/config:/data/ipfs-cluster
```

~~Everything works fine. Both nodes start and have their IPFS daemon started prior to anything else.
At this point, the JSON configuration is mostly irrelevant, we use the one auto-generated the first time we boot a peer, and always try with a clean slate when switching versions.~~

~~I'm now trying to get this to work with more recent versions if `ipfs-cluster` with no avail. I tried with `0.3.1` up to `0.3.5` (Changing `api.restapi.listen_multiaddress` to the newest field name), but it doesn't work: the IPFS API seems to never be available on `:5001`.~~

~~I tried several combinations of settings, using `127.0.0.1` or `0.0.0.0` as the binding endpoint with no cigar.~~

A few suggestions:

- I'm new to this project, and the major roadblock for us is how hard it is to understand how to get going. The concepts are clear, the architecture is well defined, but the documentation doesn't seem to be updated (For example, [this page](https://github.com/ipfs/ipfs-cluster/blob/master/docs/ipfs-cluster-guide.md) shows a JSON configuration that doesn't work because of an invalid JSON around "basic_auth_credentials" being an array instead of a dict, etc). It would be great to actually have snippets of tested config files here, because it makes their correctness doubtful. I left the Go programming language years ago so I don't quite remember if it has doctests, but I would recommend that snippets of code / configuration files would actually be the object of tests in the coverage suite, ensuring that they are maintained when something breaks them. Here we use Elixir's doctest, `## Examples` and we always have up to date docs.
- Another issue is the fact that the docker images change the configuration all the time. If you mount a JSON config file in an image, it will get changed, and edventually you'll end up with a `cluster.peers` definition that will crash your cluster on next `docker run`, because the IP of the peers change every time. A good way to solve this would be to allow netbios names instead if IP addresses in the peers specification, as for example in my fig file they all are accessible to one another as they all participate an overlay network named `ipfs`.
- Something weird too: With the configuration I gave, both nodes boot fine the first time if their data directories are clean. However, if I shut them down and restart them, they don't connect to the world, only to each other. Bummer.

Other than that, I think this project is amazing! Can't wait to see a stable release.
