### ISSUE TITLE
Potential Security Issue with CLUSTER_SECRET

### ISSUE THREAD

**Issue by hickscorp** [ipfs/ipfs-cluster#612]
Right now, the cluster secret is retrieved from ENV. It makes it trivial for anyone with read access to the docker API to read it.

It would be great to have this read in priority from a file (Eg a .env) or do like recommended by most guidelines when using Docker Secrets on a Docker Swarm: implement the `*_FILE` pattern, such as:

- The user could mount a secret and give its path to the container via `CLUSTER_SECRET_FILE` (Very much like other mainstream containers, eg mysql etc).
- The user could specify the secret via `ENV` using the `CLUSTER_SECRET` variable.

**Comment by koalalorenzo** [comment]
If reading from files you can use docker secrets to manage them. (with `CLUSTER_SECRET_FILE` as you are saying). 

But usually when using Docker and/or Kubernetes and you are required to have safe environment there are plenty of solutions like Hashicorp Vault that will take care of this.

I usually suggest to don't focus too much of this, as if the user has the power to run docker, it means that it has the power to run root (or there are wrong permissions in your machine).

**Comment by hickscorp** [comment]
@koalalorenzo I don't think it's that uncommon to see containers offer a way to interact with settings stored in files.

Mysql does (All their sensible variables have an alternative `*_FILE` correspondance), Drone does (Via a `.env` file sourced if it exists in their `entrypoint`), etc.

What I meant is that having a way to **not** have the cluster secret as part of `ENV` would really be a good idea.

**Comment by koalalorenzo** [comment]
I am not saying that there should not be an option for loading the config via a file. That is already possible. What I am saying is that if there are worries about the env being exposed then there are other worries to be scared of.

You can already load the configuration using `service.json` and ignore the ENV part. Sorry if I was not clear about that

**Comment by hickscorp** [comment]
@koalalorenzo Thanks for the feedback.
We're not interested in using `service.json` because for automatically-deployed clusters we want all the cryptographic material to be generated on the fly.
This is what we came up with:

```
version: "3.4"

services:
  node-one:
    image: ipfs/go-ipfs:release
    ports:
      - "4001:4001"
    volumes:
      - node-one:/data/ipfs

  cluster-one:
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - node-one
    ports:
      - "9094:9094"
    volumes:
      - cluster-one:/data/ipfs-cluster
    secrets:
      - source: ipfs_cluster_env
    environment:
      IPFS_API: /dns4/node-one/tcp/5001
    entrypoint: ["sh", "-c"]
    command: |
     '
     source /run/secrets/ipfs_cluster_env
     /usr/local/bin/entrypoint.sh "daemon --upgrade"
     '

  node-two:
    image: ipfs/go-ipfs:release
    ports:
      - "4101:4001"
    volumes:
      - node-two:/data/ipfs

  cluster-two:
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - cluster-one
      - node-two
    ports:
      - "9194:9094"
    volumes:
      - cluster-two:/data/ipfs-cluster
    secrets:
      - source: ipfs_cluster_env
    environment:
      IPFS_API: /dns4/node-two/tcp/5001
    entrypoint: ["sh", "-c"]
    command: |
      '
      source /run/secrets/ipfs_cluster_env
      cmd="daemon --upgrade"
      if [ ! -d /data/ipfs-cluster/raft ]; then
        while ! ipfs-cluster-ctl --host /dns4/cluster-one/tcp/9094 id; do
          sleep 1
        done
        pid=`ipfs-cluster-ctl --host /dns4/cluster-one/tcp/9094 id | grep -o -E "^(\w+)"`
        sleep 10
        cmd="daemon --bootstrap /dns4/cluster-one/tcp/9096/ipfs/$$pid"
      fi
      /usr/local/bin/entrypoint.sh $$cmd
      '

secrets:
  ipfs_cluster_env:
    external: true

volumes:
  node-one:
  node-two:
  cluster-one:
  cluster-two:
```

It requires that you push a secret to your Swarm containing something like this:

```
export CLUSTER_SECRET=whatever
```
