### ISSUE TITLE
Cluster isn't actually pinning content added via URLStore

### ISSUE THREAD

**Issue by NatoBoram** [ipfs/ipfs-cluster#701]
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
```
0.7.0+gitd80f3ee05d5688052b26556a5bb0d9cd2ea21880
```
* [x] Type (mark as appropiate):
  * [x] Bug
  * [ ] Feature request
  * [ ] Enhancement
* [x] Operating system (mark as appropiate):
```yaml
OS: Ubuntu 18.04.2 LTS x86_64 
Host: Droplet 20171212 
Kernel: 4.15.0-46-generic 
Uptime: 2 hours, 36 mins 
Packages: 677 
Shell: bash 4.4.19 
Terminal: /dev/pts/0 
CPU: Intel Xeon E5-2650L v3 (1) @ 1.797GHz 
GPU: Red Hat, Inc. QXL paravirtual graphic card 
Memory: 1089MiB / 1993MiB 
```
* [x] Installation method (mark as appropiate):
  * [ ] Binaries from dist.ipfs.io
  * [ ] Built from sources
  * [ ] Docker
  * [x] Snap
  * [ ] Other: `which?`

#### Description

I'm trying to pin about a hundred files that were previously hashed using `ipfs urlstore add`, but nothing is happening.

There's some of them stuck in `PIN_QUEUED`, `PINNING` and `PINNED`, which seems to indicates that work is being done. However, the disk usage stays the same.

![image](https://user-images.githubusercontent.com/10495562/53915501-0fd80780-402e-11e9-8ea4-a83b198bedde.png)

When trying to add new pins to the queue, I receive the following error : 

```
Failed to pin a build.
Command : ipfs-cluster-ctl pin add zdj7WcGff6a9WbgRjz37svL6BoQRyzYAe2GZLBtkPULUk6rkS --name lineage-15.1-20190221-nightly-zl1-signed.zip --replication-min 1 --replication-max 1

An error occurred:
  Code: 500
  Message: not enough peers to allocate CID. Needed at least: 1. Wanted at most: 1. Valid candidates: 0. See logs for more info.
```

But there's plenty of disk space.
